/**
 * Events
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../api';
import { Arg } from './arg';

export class Event {
    'timestamp'?: string;
    'args'?: Arg;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string"
        },
        {
            "name": "args",
            "baseName": "args",
            "type": "Arg"
        }    ];

    static getAttributeTypeMap() {
        return Event.attributeTypeMap;
    }
}

