/* 
 * Events
 *
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing Arg
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ArgTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Arg
        //private Arg instance;

        public ArgTests()
        {
            // TODO uncomment below to create an instance of Arg
            //instance = new Arg();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Arg
        /// </summary>
        [Fact]
        public void ArgInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Arg
            //Assert.IsInstanceOfType<Arg> (instance, "variable 'instance' is a Arg");
        }

        /// <summary>
        /// Test deserialize a Navigated from type Arg
        /// </summary>
        [Fact]
        public void NavigatedDeserializeFromArgTest()
        {
            // TODO uncomment below to test deserialize a Navigated from type Arg
            //Assert.IsInstanceOf<Arg>(JsonConvert.DeserializeObject<Arg>(new Navigated().ToJson()));
        }
        /// <summary>
        /// Test deserialize a VideoStarted from type Arg
        /// </summary>
        [Fact]
        public void VideoStartedDeserializeFromArgTest()
        {
            // TODO uncomment below to test deserialize a VideoStarted from type Arg
            //Assert.IsInstanceOf<Arg>(JsonConvert.DeserializeObject<Arg>(new VideoStarted().ToJson()));
        }

        /// <summary>
        /// Test the property 'ArgType'
        /// </summary>
        [Fact]
        public void ArgTypeTest()
        {
            // TODO unit test for the property 'ArgType'
        }

    }

}
