/* 
 * Events
 *
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing NavigatedAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NavigatedAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NavigatedAllOf
        //private NavigatedAllOf instance;

        public NavigatedAllOfTests()
        {
            // TODO uncomment below to create an instance of NavigatedAllOf
            //instance = new NavigatedAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NavigatedAllOf
        /// </summary>
        [Fact]
        public void NavigatedAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" NavigatedAllOf
            //Assert.IsInstanceOfType<NavigatedAllOf> (instance, "variable 'instance' is a NavigatedAllOf");
        }


        /// <summary>
        /// Test the property 'NewPath'
        /// </summary>
        [Fact]
        public void NewPathTest()
        {
            // TODO unit test for the property 'NewPath'
        }

    }

}
