/* 
 * Events
 *
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test
{
    /// <summary>
    ///  Class for testing VideoStartedAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VideoStartedAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VideoStartedAllOf
        //private VideoStartedAllOf instance;

        public VideoStartedAllOfTests()
        {
            // TODO uncomment below to create an instance of VideoStartedAllOf
            //instance = new VideoStartedAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VideoStartedAllOf
        /// </summary>
        [Fact]
        public void VideoStartedAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" VideoStartedAllOf
            //Assert.IsInstanceOfType<VideoStartedAllOf> (instance, "variable 'instance' is a VideoStartedAllOf");
        }


        /// <summary>
        /// Test the property 'VideoUrl'
        /// </summary>
        [Fact]
        public void VideoUrlTest()
        {
            // TODO unit test for the property 'VideoUrl'
        }

    }

}
