/*
 * Events
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Arg
 */
@JsonPropertyOrder({
  Arg.JSON_PROPERTY_ARG_TYPE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-03-05T14:23:16.192147+01:00[Europe/Budapest]")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "argType", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = VideoStarted.class, name = "VideoStarted"),
  @JsonSubTypes.Type(value = Navigated.class, name = "Navigated"),
})

public class Arg {
  public static final String JSON_PROPERTY_ARG_TYPE = "argType";
  private String argType;


  public Arg argType(String argType) {
    
    this.argType = argType;
    return this;
  }

   /**
   * Get argType
   * @return argType
  **/
  @ApiModelProperty(required = true, value = "")
  @JsonProperty(JSON_PROPERTY_ARG_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getArgType() {
    return argType;
  }


  public void setArgType(String argType) {
    this.argType = argType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Arg arg = (Arg) o;
    return Objects.equals(this.argType, arg.argType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(argType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Arg {\n");
    sb.append("    argType: ").append(toIndentedString(argType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

