/* 
 * Events
 *
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// NavigatedAllOf
    /// </summary>
    [DataContract]
    public partial class NavigatedAllOf :  IEquatable<NavigatedAllOf>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NavigatedAllOf" /> class.
        /// </summary>
        /// <param name="newPath">newPath.</param>
        public NavigatedAllOf(string newPath = default(string))
        {
            this.NewPath = newPath;
        }
        
        /// <summary>
        /// Gets or Sets NewPath
        /// </summary>
        [DataMember(Name="newPath", EmitDefaultValue=false)]
        public string NewPath { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NavigatedAllOf {\n");
            sb.Append("  NewPath: ").Append(NewPath).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NavigatedAllOf);
        }

        /// <summary>
        /// Returns true if NavigatedAllOf instances are equal
        /// </summary>
        /// <param name="input">Instance of NavigatedAllOf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NavigatedAllOf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NewPath == input.NewPath ||
                    (this.NewPath != null &&
                    this.NewPath.Equals(input.NewPath))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NewPath != null)
                    hashCode = hashCode * 59 + this.NewPath.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
