/*
 * Events
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NavigatedAllOf
 */
public class NavigatedAllOfTest {
    private final NavigatedAllOf model = new NavigatedAllOf();

    /**
     * Model tests for NavigatedAllOf
     */
    @Test
    public void testNavigatedAllOf() {
        // TODO: test NavigatedAllOf
    }

    /**
     * Test the property 'newPath'
     */
    @Test
    public void newPathTest() {
        // TODO: test newPath
    }

}
