/*
 * Events
 * Polymorphism example
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.openapitools.client.model.Arg;
import org.openapitools.client.model.NavigatedAllOf;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Navigated
 */
public class NavigatedTest {
    private final Navigated model = new Navigated();

    /**
     * Model tests for Navigated
     */
    @Test
    public void testNavigated() {
        // TODO: test Navigated
    }

    /**
     * Test the property 'argType'
     */
    @Test
    public void argTypeTest() {
        // TODO: test argType
    }

    /**
     * Test the property 'newPath'
     */
    @Test
    public void newPathTest() {
        // TODO: test newPath
    }

}
